### ISSUE TITLE
Stripe Tokenization

### ISSUE THREAD

**Issue by ashfurrow** [CardFlight/cardflight-v4-ios#2]
I am upgrading from version 3.6 of the SDK and the [migration docs](http://docs.cardflight.com/sdk_documentation/#migrating) specify that "vaulting" is not yet possible in v4. My question is: does vaulting include Stripe tokenization? When will vaulting support be added to the SDK? This is a blocker for us upgrading. Thanks!

**Comment by hokiewalrus** [comment]
Vaulting is a different feature from Tokenization. v4 of the SDK does support Stripe tokenization!
