### ISSUE TITLE
Signature request for tokenization flow?

### ISSUE THREAD

**Issue by ashfurrow** [CardFlight/cardflight-v4-ios#3]
Hello. I'm tokenizing cards with Stripe and I noticed that the `transaction(_: didRequest cvm:)` callback is being invoked. That doesn't make sense, because it's a tokenization process and not a transaction. And indeed, the tokenization completes without attaching a signature. So should this function be being called at all?

**Comment by hokiewalrus** [comment]
That callback is utilized for every transaction, in the case of a tokenization it will return a cvm value of CFTCVMNone, indicating no CVM is required.

If you need additional help diagnosing your specific issue, please contact support@CardFlight.com.

**Comment by ashfurrow** [comment]
Okay thanks for clarifying.
